# Generated by Django 5.2 on 2025-04-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Purchase cost per unit",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.CharField(
                blank=True, help_text="Storage location", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="maximum_stock",
            field=models.IntegerField(default=0, help_text="Maximum stock level"),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("discontinued", "Discontinued")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="minimum_stock",
            field=models.IntegerField(
                default=0, help_text="Minimum stock level before reorder"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=50, unique=True, verbose_name="SKU"),
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
    ]
