# Generated by Django 4.2.7 on 2025-04-11 14:17

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def column_exists(table, column):
    with connection.cursor() as cursor:
        cursor.execute(
            """SELECT column_name FROM information_schema.columns
               WHERE table_name = %s AND column_name = %s""",
            [table, column]
        )
        return bool(cursor.fetchone())


def add_user_field_if_not_exists(apps, schema_editor):
    # Only add the field if it doesn't already exist
    if not column_exists('products_category', 'user_id'):
        schema_editor.execute(
            "ALTER TABLE products_category ADD COLUMN user_id integer NULL REFERENCES auth_user(id) ON DELETE CASCADE;"
        )

    if not column_exists('products_product', 'user_id'):
        schema_editor.execute(
            "ALTER TABLE products_product ADD COLUMN user_id integer NULL REFERENCES auth_user(id) ON DELETE CASCADE;"
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "products",
            "0002_alter_category_options_product_barcode_product_cost_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(add_user_field_if_not_exists),
    ]
