# Generated by Django 4.2.7 on 2025-04-11 14:20

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_user_product_user"),
    ]

    def associate_products_with_users(apps, schema_editor):
        # Get the models
        Product = apps.get_model('products', 'Product')
        Category = apps.get_model('products', 'Category')
        User = apps.get_model('auth', 'User')

        # Get the first user or create one if none exists
        try:
            first_user = User.objects.first()
            if not first_user:
                # Create a default user if no users exist
                first_user = User.objects.create_user(
                    username='admin',
                    email='admin@example.com',
                    password='adminpassword'
                )

            # Associate all existing products with the first user
            Product.objects.filter(user__isnull=True).update(user=first_user)

            # Associate all existing categories with the first user
            Category.objects.filter(user__isnull=True).update(user=first_user)

        except Exception as e:
            print(f"Error associating products with users: {e}")

    operations = [
        migrations.RunPython(associate_products_with_users),
    ]
