# Generated by Django 5.2 on 2025-04-12 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_sale_saleitem_savedreport_userpreference_inventorysnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="dashboard_widgets",
            field=models.JSONField(default=dict),
        ),
    ]
